#!/usr/bin/env python3
"""Build the portable audit review from captured evidence, not Hub runtime."""
from pathlib import Path
import json,re,html
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
inv=json.loads((HERE/'inventory.json').read_text())
findings=json.loads((HERE/'findings.json').read_text())
# Candidate table ledger is deliberately separate from reviewed findings.
rows={}
for c in inv['candidates']:
 if c['category']=='raw-table' and c['path'].endswith('.svelte'):
  rows.setdefault(c['path'],[]).append(c['line'])
ledger=['# Table discovery and concurrent ownership','','The table migration belongs to the concurrent Claude session. These are raw `<table` text matches in the scanned checkout, including strings/comments. They are neither a migration checklist nor confirmed defects. Re-run the scan after the cell-edit work lands.','','| Source | Lines | Disposition |','|---|---|---|']
for path,lines in sorted(rows.items()):
 special=any(s in path for s in ('charts/Chart.svelte','ui/Picker.svelte','chat/MarkdownMessage.svelte','data-table/DataTable.svelte'))
 tooltip=path.endswith('/reliability/+page.svelte')
 disposition='Shared renderer or specialized generated/accessibility surface; preserve unless semantic review proves otherwise' if special else 'HTML tooltip string; not an interactive data-table migration' if tooltip else 'Reserved for Claude; classify display, editor, comparison or matrix before migration'
 ledger.append(f"| [{path}](../../{path}) | {', '.join(map(str,lines))} | {disposition} |")
ledger+=['','Server email tables are excluded from this UI ledger. The broad inventory retains their matches for transparent counting. No table source was modified.','']
(HERE/'TABLES.md').write_text('\n'.join(ledger))
css=(ROOT/'packages/design-tokens/tokens.css').read_text()
tokens=re.search(r'@theme static\s*\{([\s\S]*?)\n\}',css).group(1)
data=json.dumps({'findings':findings,'inventory':[{k:v for k,v in x.items() if k in ('path','kind','exports','direct_consumers')} for x in inv['inventory']]},ensure_ascii=False).replace('<','\\u003c')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Hub centralization audit</title>
<style>:root{TOKENS}*{box-sizing:border-box}body{margin:0;background:var(--color-canvas);color:var(--color-text-primary);font:14px/1.55 var(--font-family-sans)}main{max-width:1280px;margin:auto;padding:32px 24px 80px}header{max-width:880px;margin-bottom:32px}h1{font:600 32px/1.2 var(--font-family-display);letter-spacing:-.02em;margin:12px 0}h2{font-size:18px;margin:0 0 12px}h3{font-size:16px;margin:10px 0}p{color:var(--color-text-secondary);margin:8px 0}a{color:var(--color-info-fg)}.eyebrow{color:var(--color-info-fg);text-transform:uppercase;letter-spacing:.1em;font-size:12px}.notice{padding:14px 18px;border:1px solid var(--color-warning-border);background:var(--color-warning-surface);color:var(--color-warning-fg);border-radius:8px}.metrics,.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:24px 0}.card,section{min-width:0;background:var(--color-surface-1);border:1px solid var(--color-border-default);border-radius:12px;padding:20px}.metric{font-size:28px;font-weight:600}.muted{color:var(--color-text-tertiary);font-size:12px}section{margin:24px 0}.toolbar{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:16px 0}input,select,button{font:inherit;color:inherit;background:var(--color-surface-2);border:1px solid var(--color-border-strong);border-radius:6px;padding:9px 12px;min-width:0}input{flex:1;min-width:180px}button{cursor:pointer}button.active{color:var(--color-info-fg);border-color:var(--color-info-fg)}:focus-visible{outline:2px solid var(--color-info-fg);outline-offset:3px}.tablewrap{width:100%;overflow:auto}table{border-collapse:collapse;width:100%;table-layout:fixed}th,td{text-align:left;vertical-align:top;border-bottom:1px solid var(--color-border-default);padding:14px 10px;overflow-wrap:anywhere}th{color:var(--color-text-tertiary);font-size:12px}td small{display:block;color:var(--color-text-secondary);margin-top:6px}.pill{font-size:11px;display:inline-block;border-radius:99px;padding:3px 8px;background:var(--color-surface-3);color:var(--color-text-secondary)}.p1{color:var(--color-warning-fg);background:var(--color-warning-surface)}.path{font-family:var(--font-family-mono);font-size:11px;overflow-wrap:anywhere;color:var(--color-text-tertiary)}.step{border-top:2px solid var(--color-accent);padding-top:12px}.stack{display:grid;grid-template-columns:minmax(0,1fr);gap:14px}.stack article{border-bottom:1px solid var(--color-border-default);padding:12px 0;min-width:0}.stack p{overflow-wrap:anywhere}.hidden{display:none}summary{cursor:pointer;color:var(--color-info-fg)}footer{font-size:12px;color:var(--color-text-tertiary)}@media(max-width:720px){main{padding:20px 12px}.metrics,.grid{grid-template-columns:minmax(0,1fr)}h1{font-size:26px}th,td{padding:10px 5px}section{padding:14px}}
</style><main><header><div class="eyebrow">Minion Hub · Source audit · 20 September 2026</div><h1>Shared behavior.<br>Consistent changes across views.</h1><p>The foundations already exist. The next step is consistent adoption, versioned mutations and committed-change propagation. Removing Save buttons comes after those contracts work.</p></header>
<div class="notice">Audit completed · Consolidation proposed · Claude owns the table migration · Existing POS work preserved</div>
<div class="metrics"><div class="card"><div class="metric">492</div><p>Component files indexed</p></div><div class="card"><div class="metric">194</div><p>Service-directory files indexed</p></div><div class="card"><div class="metric">22</div><p>Reviewed consolidation findings</p></div></div>
<p class="muted">2,812 source files scanned, including meta packages; 661 additional shared-module entries. Counts describe source files, not APIs or defects. Pattern candidates are not all semantically reviewed.</p>
<section><h2>What needs to change first</h2><div class="grid"><div class="step"><h3>1 · Reliable writes</h3><p>Use shared error handling. Reject stale writes atomically. An old save response must never clear a newer draft.</p></div><div class="step"><h3>2 · Propagate commits</h3><p>Map entity changes to page dependencies, query keys and local caches. Extend the existing private org channel and recover after missed signals.</p></div><div class="step"><h3>3 · Consolidate invariants</h3><p>Unify party validation, recipe resolution and tagging contracts. Extend shared UI where variants differ, then migrate callers.</p></div></div></section>
<section><h2>Reviewed findings</h2><p>Every row has a source anchor, a chosen consolidation boundary and a next action. Source evidence only; no runtime failures are claimed as reproduced.</p><div class="toolbar"><input id="search" aria-label="Search findings" placeholder="Search tags, recipes, dates, autosave…"><select id="domain" aria-label="Filter domain"><option>All domains</option><option>Services</option><option>Freshness</option><option>Components</option></select><select id="priority" aria-label="Filter priority"><option>All priorities</option><option>P1</option><option>P2</option><option>P3</option></select></div><p id="count" class="muted" aria-live="polite"></p><div id="findings" class="stack"></div></section>
<section><h2>The Notion-style editing contract</h2><div class="grid"><div><h3>Autosave ordinary properties</h3><p>Names, reversible scalar values and manual tags commit on blur, Enter, selection or bounded debounce. Show pending, saved, error and conflict states.</p></div><div><h3>Keep explicit commitments</h3><p>Multi-field forms, payments, invoice issuance, stock posting, deletion and cancellation keep submit or confirmation actions.</p></div><div><h3>Verify across representations</h3><p>Two views, two tabs and two authorized users converge on one committed version. A foreign organization receives no record details. Reconnect repairs missed changes.</p></div></div></section>
<section><h2>Full source index</h2><p>Search the captured component, service and shared-module index. Consumer counts are direct imports; barrel exports are not traversed. Zero does not prove dead code.</p><div class="toolbar"><input id="indexSearch" aria-label="Search source index" placeholder="Search paths or exported symbols…"><select id="kind" aria-label="Filter source kind"><option>All kinds</option><option>component</option><option>service</option><option>shared-module</option></select></div><p id="indexCount" class="muted" aria-live="polite"></p><div id="inventory" class="stack"></div><button id="more">Show more results</button></section>
<section><h2>Preserve deliberate differences</h2><p>Invoice ingestion and emission are different operations. Contact auto-tags retain their own metadata. SvelteKit business loads, gateway push state, client query cache and server cache have different owners. Statistical control bands, stock illustrations and accessibility tables are legitimate specialized renderers.</p><p>The Hub consumes a tarball of <span class="path">@minion-stack/ui</span>; editing the meta package alone does not update the app.</p></section>
<footer>Snapshot: Hub master 0acd6282df74d18eacd27673fcf238cd16a29e56 plus working-tree changes. No Hub source changes, production operations or runtime/UI validation in this audit. Design source: Minion design-tokens package, matched to the audited project. Full evidence: audits/2026-09-20-hub-centralization/README.md and sibling domain reports. Draft proposal: proposals/2026-09-20-hub-component-service-centralization.md.</footer></main>
<script id="audit-data" type="application/json">DATA</script><script>
const data=JSON.parse(document.getElementById('audit-data').textContent);const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const q=$('search').value.toLowerCase();const rows=data.findings.filter(f=>JSON.stringify(f).toLowerCase().includes(q)&&($('domain').value==='All domains'||f.domain===$('domain').value)&&($('priority').value==='All priorities'||f.priority===$('priority').value));$('count').textContent=rows.length+' of '+data.findings.length+' reviewed findings';$('findings').innerHTML=rows.map(f=>`<article id="${esc(f.id)}"><span class="pill ${f.priority==='P1'?'p1':''}">${esc(f.id)} · ${esc(f.priority)} · ${esc(f.domain)}</span><h3>${esc(f.title)}</h3><p>${esc(f.detail)}</p><div class="path">minion_hub/${esc(f.source)}</div><p><strong>${esc(f.mode)}:</strong> ${esc(f.target)}</p><p>${esc(f.action)}</p></article>`).join('')||'<p>No findings match these filters.</p>';}
let limit=40;function renderIndex(reset=false){if(reset)limit=40;const q=$('indexSearch').value.toLowerCase();const rows=data.inventory.filter(x=>(x.path+' '+x.exports.join(' ')).toLowerCase().includes(q)&&($('kind').value==='All kinds'||x.kind===$('kind').value));$('indexCount').textContent=`Showing ${Math.min(limit,rows.length)} of ${rows.length} matching entries`;$('inventory').innerHTML=rows.slice(0,limit).map(x=>`<article><span class="pill">${esc(x.kind)} · ${x.direct_consumers.length} direct consumer files</span><p class="path">${esc(x.path)}</p>${x.exports.length?`<p>${esc(x.exports.join(', '))}</p>`:''}${x.direct_consumers.length?`<details><summary>Show callers</summary><p class="path">${x.direct_consumers.map(esc).join('<br>')}</p></details>`:''}</article>`).join('');$('more').hidden=limit>=rows.length;}
for(const id of ['search','domain','priority'])$(id).addEventListener('input',render);for(const id of ['indexSearch','kind'])$(id).addEventListener('input',()=>renderIndex(true));$('more').addEventListener('click',()=>{limit+=40;renderIndex();});render();renderIndex();
</script></html>'''.replace('TOKENS',tokens).replace('DATA',data)
out=ROOT/'.lavish/hub-centralization-2026-09-20.html';out.write_text(page);print(out)
