#!/usr/bin/env python3
"""Rebuild a lexical source inventory; candidates require semantic review.
Run from any directory. Does not write Hub source or resolve runtime imports.
"""
from pathlib import Path
import re, json, hashlib, subprocess, datetime
HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
HUB = ROOT / 'minion_hub'
def git(path, *args):
    return subprocess.check_output(['git', '-C', str(path), *args], text=True).strip()
def rel(p): return p.relative_to(ROOT).as_posix()
paths = sorted(p for base in [HUB/'src', ROOT/'packages'] for p in base.rglob('*')
               if p.suffix in ('.ts','.svelte','.js','.mjs','.css') and not any(x in p.parts for x in ('node_modules','dist','.svelte-kit')))
texts = {rel(p):p.read_text(errors='replace') for p in paths}
def is_test(s): return any(x in s for x in ('.test.', '.spec.', '/__tests__/', '/_test/', '/test-utils/'))
imports = []
for path, body in texts.items():
    for match in re.finditer(r'''(?:\bfrom\s*|\bimport\s*\(\s*|\bimport\s*)["']([^"']+)["']''',body):
        spec = match.group(1)
        base = HUB/'src/lib'/spec[5:] if spec.startswith('$lib/') else HUB/'src/server'/spec[8:] if spec.startswith('$server/') else (ROOT/path).parent/spec if spec.startswith('.') else None
        target = None
        if base:
            for p in [base,Path(str(base)+'.ts'),Path(str(base)+'.svelte'),base/'index.ts',Path(str(base)+'.js')]:
                if p.is_file(): target = rel(p.resolve()); break
        imports.append(dict(source=path,line=body.count('\n',0,match.start())+1,specifier=spec,target=target,test=is_test(path)))
bytarget = {}
for i in imports:
    if i['target'] and not i['test']: bytarget.setdefault(i['target'],set()).add(i['source'])
inventory=[]
for path,body in texts.items():
    if is_test(path): continue
    kind = 'component' if '/components/' in path and path.endswith('.svelte') or path.startswith('packages/ui/') and path.endswith('.svelte') else 'service' if '/services/' in path else 'shared-module' if path.startswith('packages/') or any('/'+x+'/' in path for x in ('api','query','realtime','events','cache')) else None
    if not kind: continue
    inventory.append(dict(path=path,kind=kind,sha256=hashlib.sha256(body.encode()).hexdigest(),lines=len(body.splitlines()),direct_consumers=sorted(bytarget.get(path,[])),exports=sorted(set(re.findall(r'\bexport\s+(?:async\s+)?(?:function|const|class|type|interface)\s+(\w+)',body)))))
patterns={
 'raw-table':r'<table\b', 'native-date-input':r'type\s*=\s*["\'](?:date|datetime-local|month)["\']',
 'native-select':r'<select\b', 'native-button':r'<button\b', 'native-textarea':r'<textarea\b',
 'direct-echarts':r'(?:echarts\.init\s*\(|from\s*["\']echarts(?:/[^"\']*)?["\'])',
 'manual-dialog':r'role\s*=\s*["\'](?:dialog|alertdialog)["\']',
 'fetch':r'\bfetch\s*\(', 'polling':r'\bsetInterval\s*\(',
 'broad-invalidation':r'\binvalidateAll\s*\(', 'local-event':r'(?:dispatchEvent\s*\(|new\s+(?:CustomEvent|EventSource)\s*\()',
 'tag-storage':r'\b(?:tagLinks|entityTags|crmTags|contactTags)\b',
 'sql-access-in-route':r'(?:\b(?:db|tx)\.(?:select|insert|update|delete|execute)\s*\(|\bpg\s*`)',
}
candidates=[]
for path,body in texts.items():
    if is_test(path) or not path.startswith('minion_hub/src/'): continue
    for category,pattern in patterns.items():
        if category=='sql-access-in-route' and '/routes/' not in path: continue
        for line,text in enumerate(body.splitlines(),1):
            if re.search(pattern,text): candidates.append(dict(category=category,path=path,line=line,excerpt=text.strip()[:240]))
data=dict(generated_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),scope='Lexical inventory, not runtime proof. Direct import counts exclude tests and do not traverse barrels. Pattern hits include legitimate primitives, comments and specialized renderers.',hub_head=git(HUB,'rev-parse','HEAD'),hub_branch=git(HUB,'branch','--show-current'),meta_head=git(ROOT,'rev-parse','HEAD'),hub_status=git(HUB,'status','--short'),source_files=len(texts),inventory=inventory,imports=imports,candidates=candidates,source_hashes={p:hashlib.sha256(s.encode()).hexdigest() for p,s in texts.items()})
(HERE/'inventory.json').write_text(json.dumps(data,indent=2)+'\n')
counts={k:sum(i['kind']==k for i in inventory) for k in ('component','service','shared-module')}
lines=['# Hub source inventory','','Generated by `python3 audits/2026-09-20-hub-centralization/scan.py`.','','This is a lexical index. An import through a barrel is counted against the barrel, not each export. Zero direct consumers does not prove dead code. Pattern hits are candidates, not confirmed defects. The accompanying report contains reviewed findings.','',f"Hub `{data['hub_head']}` on `{data['hub_branch']}`, including working-tree changes.",'',str(counts),'']
for kind in counts:
    lines += ['## '+kind,'','| Source | Direct consumer files | Exported symbols |','|---|---:|---|']
    for item in inventory:
        if item['kind']==kind: lines.append(f"| [{item['path']}](../../{item['path']}) | {len(item['direct_consumers'])} | {', '.join(item['exports'])} |")
    lines.append('')
(HERE/'INDEX.md').write_text('\n'.join(lines))
print(json.dumps(dict(source_files=len(texts),inventory=counts,candidates={k:sum(c['category']==k for c in candidates) for k in patterns}),indent=2))
