import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import {
  flattenFoundations,
  generatedCssPath,
  readContract,
  resolveTheme,
} from './contract.mjs';

function declaration([token, value], indent = '  ') {
  return `${indent}${token}: ${value};`;
}

function aliasDeclarations(contract) {
  return [...Object.entries(contract.aliases), ...Object.entries(contract.domainAliases)].map(
    ([alias, target]) => [alias, `var(${target})`],
  );
}

export function generateCss(contract) {
  const defaultTheme = resolveTheme(contract, contract.defaultTheme);
  const themeBlocks = Object.entries(contract.themes)
    .filter(([themeId]) => themeId !== contract.defaultTheme)
    .map(([themeId, theme]) => {
      const selector = `:root[data-minion-theme='${themeId}'],\n:root[data-theme-preset='${themeId}']`;
      const declarations = resolveTheme(contract, themeId).map((entry) => declaration(entry)).join('\n');
      return `${selector} {\n  color-scheme: ${theme.mode};\n${declarations}\n}`;
    })
    .join('\n\n');

  const defaultMode = contract.themes[contract.defaultTheme].mode;
  const foundationDeclarations = flattenFoundations(contract);
  const sharedDeclarations = [
    ...foundationDeclarations,
    ...Object.entries(contract.palettes),
    ...defaultTheme,
    ...aliasDeclarations(contract),
  ];

  return `/*
 * @minion-stack/design-tokens
 * GENERATED from contract.json by scripts/generate-css.mjs.
 * Do not edit this file by hand; run \`pnpm generate\` in this package.
 */

@theme static {
${sharedDeclarations.map((entry) => declaration(entry)).join('\n')}
}

:root {
  color-scheme: ${defaultMode};
}

${themeBlocks}

@media (min-width: ${contract.responsive.mediumMin}) {
  :root {
    --space-page-gutter: ${contract.responsive.pageGutter.medium};
  }
}

@media (min-width: ${contract.responsive.wideMin}) {
  :root {
    --space-page-gutter: ${contract.responsive.pageGutter.wide};
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-instant: 0ms;
    --duration-fast: 0ms;
    --duration-normal: 0ms;
    --duration-slow: 0ms;
  }
}
`;
}

export async function main(args = process.argv.slice(2)) {
  const contract = await readContract();
  const generated = generateCss(contract);
  if (args.includes('--check')) {
    const current = await readFile(generatedCssPath, 'utf8').catch(() => '');
    if (current !== generated) {
      throw new Error('tokens.css is stale. Run `pnpm --filter @minion-stack/design-tokens generate`.');
    }
    return;
  }
  await writeFile(generatedCssPath, generated, 'utf8');
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
