// Plugin scaffold templates (Phase 28, CLI-01..04).
//
// `minion plugin new <id> --template={basic,channel,rpc}` generates a working,
// typed Minion gateway plugin under `minion/extensions/<id>/`. Every template
// ships the MODERN SDK patterns out of the box (CLI-04):
//   - `defineManifest({...})` in minion.manifest.ts (Phase 26) — single source of
//     truth for config; `minion.plugin.json` is generated by the gateway build.
//   - package-style imports from `minion/plugin-sdk` + `minion/plugin-sdk/test`
//     (Phase 22 namespaced surface) — no fragile relative `../../src/...` paths.
//   - `api.rpc.define(...)` (Phase 25) for the rpc template.
//   - `api.registerChannelLink(...)` (Phase 27) for the channel template.
// A scaffolded test uses the shared harness (Phase 24) so the plugin is verifiable
// with zero manual edits.

import * as fs from 'node:fs';
import * as path from 'node:path';

export type PluginTemplate = 'basic' | 'channel' | 'rpc';

export const PLUGIN_TEMPLATES: readonly PluginTemplate[] = ['basic', 'channel', 'rpc'] as const;

export interface ScaffoldFile {
	/** Path relative to the plugin directory. */
	path: string;
	content: string;
}

export interface ScaffoldOptions {
	description?: string;
}

const ID_RE = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

/** Validate a plugin id: lowercase kebab-case, leading letter. Throws on bad input. */
export function assertValidPluginId(id: string): void {
	if (!ID_RE.test(id)) {
		throw new Error(
			`Invalid plugin id '${id}'. Use lowercase kebab-case starting with a letter (e.g. "my-plugin").`,
		);
	}
}

/** "my-plugin" → "MyPlugin" */
export function pascalCase(id: string): string {
	return id
		.split('-')
		.filter(Boolean)
		.map((p) => p.charAt(0).toUpperCase() + p.slice(1))
		.join('');
}

/** "my-plugin" → "myPlugin" */
export function camelCase(id: string): string {
	const pascal = pascalCase(id);
	return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function packageJson(id: string, description: string): string {
	return `${JSON.stringify(
		{
			name: `@minion/${id}`,
			version: '2026.1.0',
			private: true,
			description,
			type: 'module',
			scripts: { test: 'vitest run' },
			devDependencies: { '@nikolasp98/minion': 'workspace:*' },
			minion: { extensions: ['./index.ts'] },
		},
		null,
		2,
	)}\n`;
}

function basicTemplate(id: string, description: string): ScaffoldFile[] {
	const Name = pascalCase(id);
	const tool = `${camelCase(id)}_echo`;
	return [
		{
			path: 'minion.manifest.ts',
			content: `// ${Name} plugin manifest. Edit THIS file, never the generated minion.plugin.json.
// The gateway build runs codegen (scripts/generate-plugin-manifests.ts) to emit
// minion.plugin.json from this single source of truth.

import { defineManifest } from "minion/plugin-sdk";

const manifest = defineManifest({
  id: "${id}",
  name: "${Name}",
  description: ${JSON.stringify(description)},
});

export default manifest;
`,
		},
		{
			path: 'index.ts',
			content: `import { Type } from "@sinclair/typebox";
import type { MinionPluginApi } from "minion/plugin-sdk";

// A "basic" plugin: contributes a single agent tool. Swap the tool body for your
// own logic, add more tools, or run \`minion plugin new <id> --template=rpc\` for a
// gateway-RPC starter / \`--template=channel\` for a channel-pairing starter.
const plugin = {
  id: "${id}",
  name: "${Name}",
  description: ${JSON.stringify(description)},
  register(api: MinionPluginApi) {
    api.registerTool({
      name: "${tool}",
      label: "${Name} Echo",
      description: "Example tool — echoes the provided message back.",
      parameters: Type.Object({
        message: Type.String({ description: "Text to echo back." }),
      }),
      async execute(_id: string, params: unknown) {
        const input = params as { message?: unknown };
        const message = typeof input.message === "string" ? input.message : "";
        const reply = \`${id}: \${message}\`;
        return {
          content: [{ type: "text" as const, text: reply }],
          details: { reply },
        };
      },
    });
  },
};

export default plugin;
`,
		},
		{
			path: `${id}.test.ts`,
			content: `import { captureRegistrations } from "minion/plugin-sdk/test";
import { describe, expect, it } from "vitest";
import plugin from "./index.js";

describe("${id} plugin", () => {
  it("registers the ${tool} tool that echoes its input", async () => {
    const { tools } = await captureRegistrations(plugin);
    expect(tools).toHaveLength(1);

    const entry = tools[0];
    // The basic template registers a plain tool (not a factory).
    const tool = entry?.tool as {
      name: string;
      execute: (id: string, params: Record<string, unknown>) => Promise<{ details: unknown }>;
    };
    expect(tool.name).toBe("${tool}");

    const res = await tool.execute("call1", { message: "ping" });
    expect(res.details).toEqual({ reply: "${id}: ping" });
  });
});
`,
		},
	];
}

function rpcTemplate(id: string, description: string): ScaffoldFile[] {
	const Name = pascalCase(id);
	const method = `${id}.greet`;
	return [
		{
			path: 'minion.manifest.ts',
			content: `// ${Name} plugin manifest. Edit THIS file, never the generated minion.plugin.json.

import { defineManifest } from "minion/plugin-sdk";

const manifest = defineManifest({
  id: "${id}",
  name: "${Name}",
  description: ${JSON.stringify(description)},
});

export default manifest;
`,
		},
		{
			path: 'index.ts',
			content: `import { Type } from "@sinclair/typebox";
import type { MinionPluginApi } from "minion/plugin-sdk";

// An "rpc" plugin: exposes a typed gateway RPC via \`api.rpc.define\` (Phase 25).
// params/result are TypeBox schemas — params are validated before the handler
// runs, the result is validated before responding, and a thrown error is turned
// into a structured \`{ ok: false, error }\` envelope. No try/catch or manual
// respond() boilerplate. Hub callers can import a typed contract for end-to-end
// autocomplete (see RPC-03 / extensions/whatsapp/src/rpc-contract.ts).
const plugin = {
  id: "${id}",
  name: "${Name}",
  description: ${JSON.stringify(description)},
  register(api: MinionPluginApi) {
    api.rpc.define({
      method: "${method}",
      params: Type.Object({
        name: Type.String({ description: "Who to greet." }),
      }),
      result: Type.Object({
        greeting: Type.String(),
      }),
      handler: ({ params }) => ({ greeting: \`Hello, \${params.name}!\` }),
    });
  },
};

export default plugin;
`,
		},
		{
			path: `${id}.test.ts`,
			content: `import { captureRegistrations } from "minion/plugin-sdk/test";
import { describe, expect, it } from "vitest";
import plugin from "./index.js";

describe("${id} plugin", () => {
  it("registers the ${method} typed RPC and greets the caller", async () => {
    const { rpc, gatewayMethods } = await captureRegistrations(plugin);
    expect(rpc).toHaveLength(1);

    const handler = gatewayMethods["${method}"];
    expect(typeof handler).toBe("function");

    let payload: unknown;
    await handler({
      params: { name: "Ada" },
      respond: (_ok: boolean, body?: unknown) => {
        payload = body;
      },
    } as never);
    expect(payload).toEqual({ greeting: "Hello, Ada!" });
  });

  it("rejects params that fail validation", async () => {
    const { gatewayMethods } = await captureRegistrations(plugin);
    const handler = gatewayMethods["${method}"];

    let ok: boolean | undefined;
    await handler({
      params: {},
      respond: (responded: boolean) => {
        ok = responded;
      },
    } as never);
    expect(ok).toBe(false);
  });
});
`,
		},
	];
}

function channelTemplate(id: string, description: string): ScaffoldFile[] {
	const Name = pascalCase(id);
	return [
		{
			path: 'minion.manifest.ts',
			content: `// ${Name} channel plugin manifest. Edit THIS file, never the generated
// minion.plugin.json. The \`channelLink\` descriptor tells the hub how to render
// the linking UI; the gateway derives the matching method/event names from the
// channel id (Phase 27), and the loader warns if this manifest declares a
// channelLink but \`register()\` doesn't call \`api.registerChannelLink\` (or vice
// versa).

import { defineManifest } from "minion/plugin-sdk";

const manifest = defineManifest({
  id: "${id}",
  name: "${Name}",
  description: ${JSON.stringify(description)},
  channels: ["${id}"],
  channelLink: {
    mode: "qr",
    label: "${Name}",
    description: "Scan a QR code to link your ${Name} account.",
    startMethod: "channels.${id}.pair",
    qrEvent: "channels.${id}.qr",
    pairedEvent: "channels.${id}.paired",
    failedEvent: "channels.${id}.pairFailed",
  },
});

export default manifest;
`,
		},
		{
			path: 'index.ts',
			content: `import type { MinionPluginApi } from "minion/plugin-sdk";

// A "channel" plugin: declarative QR pairing via \`api.registerChannelLink\`
// (Phase 27). The SDK derives the gateway method (\`channels.${id}.pair\`) and the
// qr/paired/failed event names from the channel id and auto-acks the request —
// you never type those magic strings. Drive your real login engine inside \`pair\`
// and broadcast progress with the \`emitQr/emitPaired/emitFailed\` helpers.
const plugin = {
  id: "${id}",
  name: "${Name}",
  description: ${JSON.stringify(description)},
  register(api: MinionPluginApi) {
    api.registerChannelLink({
      mode: "qr",
      pair: ({ emitQr, emitPaired, emitFailed }) => {
        try {
          // TODO: start your channel's login flow and stream its QR codes here.
          emitQr({ qrData: "replace-with-real-qr-payload" });
          // When the device finishes linking:
          emitPaired({ ok: true });
        } catch (err) {
          emitFailed({ message: err instanceof Error ? err.message : String(err) });
        }
      },
    });
  },
};

export default plugin;
`,
		},
		{
			path: `${id}.test.ts`,
			content: `import { createTestApi } from "minion/plugin-sdk/test";
import { describe, expect, it } from "vitest";
import plugin from "./index.js";

describe("${id} channel plugin", () => {
  it("registers a QR channel link with the derived pair method", () => {
    const api = createTestApi({ id: "${id}" });
    plugin.register(api);

    expect(api.registrations.channelLinks).toHaveLength(1);
    // The SDK derives the gateway method name from the channel id.
    expect(api.registrations.gatewayMethods).toHaveProperty("channels.${id}.pair");
  });
});
`,
		},
	];
}

function readme(id: string, template: PluginTemplate, description: string): string {
	const blurbs: Record<PluginTemplate, string> = {
		basic: `This plugin contributes a single agent tool (\`${camelCase(id)}_echo\`). Edit \`index.ts\` to add your own tools.`,
		rpc: `This plugin exposes a typed gateway RPC (\`${id}.greet\`) via \`api.rpc.define\`. Params and results are validated against TypeBox schemas.`,
		channel: `This plugin provides a \`${id}\` channel with QR-code pairing via \`api.registerChannelLink\`. Wire your real login engine into the \`pair\` handler in \`index.ts\`.`,
	};
	return `# @minion/${id}

> ${description}

${blurbs[template]}

## Layout

| File | Purpose |
|---|---|
| \`minion.manifest.ts\` | Single source of truth for the manifest (\`defineManifest\`). The gateway build generates \`minion.plugin.json\` from it. |
| \`index.ts\` | Plugin entry — \`register(api)\` wires up the plugin's contributions. |
| \`${id}.test.ts\` | Tests using the shared \`minion/plugin-sdk/test\` harness. |

## Develop

From the gateway repo root (\`minion/\`):

\`\`\`bash
pnpm install
pnpm build          # regenerates minion.plugin.json from minion.manifest.ts
pnpm test           # runs this plugin's tests via the workspace vitest
\`\`\`

Generated by \`minion plugin new ${id} --template=${template}\`.
`;
}

/** Build the in-memory file set for a scaffold. Pure — no disk writes. */
export function buildScaffold(
	id: string,
	template: PluginTemplate,
	opts: ScaffoldOptions = {},
): ScaffoldFile[] {
	assertValidPluginId(id);
	const description =
		opts.description ?? `${pascalCase(id)} plugin for the Minion gateway (${template} template).`;

	const files: ScaffoldFile[] =
		template === 'rpc'
			? rpcTemplate(id, description)
			: template === 'channel'
				? channelTemplate(id, description)
				: basicTemplate(id, description);

	files.push({ path: 'package.json', content: packageJson(id, description) });
	files.push({ path: 'README.md', content: readme(id, template, description) });
	return files;
}

export interface WriteScaffoldResult {
	dir: string;
	files: string[];
}

/**
 * Write a scaffold to `targetDir`. Throws if the directory already exists with
 * conflicting files (unless `force`). Creates parent directories as needed.
 */
export function writeScaffold(
	targetDir: string,
	files: ScaffoldFile[],
	opts: { force?: boolean } = {},
): WriteScaffoldResult {
	if (fs.existsSync(targetDir) && fs.readdirSync(targetDir).length > 0 && !opts.force) {
		throw new Error(
			`Target directory '${targetDir}' already exists and is not empty. Pass --force to overwrite.`,
		);
	}
	fs.mkdirSync(targetDir, { recursive: true });
	const written: string[] = [];
	for (const file of files) {
		const dest = path.join(targetDir, file.path);
		fs.mkdirSync(path.dirname(dest), { recursive: true });
		fs.writeFileSync(dest, file.content, 'utf8');
		written.push(file.path);
	}
	return { dir: targetDir, files: written };
}
