import { pgTable, uuid, text, boolean, timestamp, jsonb, index, uniqueIndex } from 'drizzle-orm/pg-core';

/**
 * Universal, org-scoped message ledger. Every comms channel writes here via the
 * gateway outbox → hub ingest path. Standard columns are the cross-channel
 * intersection; anything channel-specific goes in `metadata`.
 *
 * RLS (org isolation) is added in the hand-written companion migration
 * `<ts>_messages_rls.sql` (role app_ledger + app.current_org_id GUC). Drizzle
 * does not manage roles/policies.
 */
export const messages = pgTable(
  'messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // Ingest idempotency key, generated by the gateway per row.
    clientId: text('client_id').notNull(),
    // RLS pivot. Better Auth org id (text), matches flows.tenant_id convention.
    orgId: text('org_id').notNull(),
    // Producing gateway/server id (hub servers.id; text — not a PG uuid).
    gatewayId: text('gateway_id'),
    direction: text('direction', { enum: ['inbound', 'outbound'] }).notNull(),
    channel: text('channel').notNull(),
    accountId: text('account_id'),
    chatId: text('chat_id'),
    isGroup: boolean('is_group'),
    senderId: text('sender_id'),
    senderName: text('sender_name'),
    senderHandle: text('sender_handle'),
    isBot: boolean('is_bot'),
    content: text('content'),
    messageId: text('message_id'),
    agentId: text('agent_id'),
    sessionKey: text('session_key'),
    success: boolean('success'),
    error: text('error'),
    occurredAt: timestamp('occurred_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    metadata: jsonb('metadata').notNull().default({}),
  },
  (t) => ({
    clientIdUnique: uniqueIndex('messages_client_id_uniq').on(t.clientId),
    orgChatIdx: index('messages_org_chat_idx').on(t.orgId, t.channel, t.chatId, t.occurredAt),
    orgTimeIdx: index('messages_org_time_idx').on(t.orgId, t.occurredAt),
    orgAgentIdx: index('messages_org_agent_idx').on(t.orgId, t.agentId),
    messageIdIdx: index('messages_message_id_idx').on(t.messageId),
  }),
);
