#!/usr/bin/env python3
from pathlib import Path
import json
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[1]
# Each tuple: ID, family, source, source needle, policy, immediate response, settlement, commit gesture.
rows=[
('A01','Module navigation','src/routes/(app)/+layout.svelte','moduleKey','R','Select destination immediately; keep shell, scroll owner and current content until keyed target content is ready.','Only newest navigation may replace active view; failed load offers retry.','No Save'),
('A02','Search, filters, sort and paging','src/lib/components/data-table/DataTable.svelte','ServerQuery','R','Update control intent; keep prior keyed results marked refreshing, or render matching cached results.','Latest query generation wins; never label old data as the newly requested result.','No Save'),
('A03','Date ranges and chart refresh','src/lib/components/dashboard/DateRangeControls.svelte','<script','R','Update selected interval immediately; preserve chart instance and axes where meaningful.','Apply canonical matching-range data; stale interval responses cannot replace selection.','No Save'),
('A04','POS calendar view/date navigation','src/routes/(app)/pos/appointments/+page.svelte','function','R','Day/work-week/week, Today and arrows react on input; retain layout and show only matching cached windows.','Selected interval has keyed loading/error; reconcile URL Back/Forward.','No Save'),
('A05','Calendar split, staff, kinds and inherited tags','src/lib/components/scheduling/calendar/CalendarToolbar.svelte','<script','L/R/O','Split lanes/filter intent updates immediately; local filtering has no network wait.','Persist only declared preferences; failure marks preference unsynced without relabeling booking facts.','No Save'),
('A06','POS booking drag and resize','src/lib/components/scheduling/BookingCalendar.svelte','async','O','Keep dropped/resized chip at target after pointer release with pending outline.','Canonical booking/version replaces overlay; known conflict reverts affected move and preserves retry intent.','Drop commits; exceptions reviewed'),
('A07','Scheduling booking drag and resize','src/lib/components/scheduling/calendar/MoveConfirmDialog.svelte','<script','O/C','Ordinary single-booking move commits on drop, reusing shared overlay; conditional review handles series/override.','Same operation rules as POS; remove routine Save modal only after server capability gates pass.','Drop commits; conditional confirmation'),
('A08','Paid line dropped into calendar','src/routes/(app)/pos/appointments/+page.svelte','async function','C','Reserve tray item locally and insert provisional booking with stable key, labeled creating.','Paid line identity deduplicates creation; conflict restores tray/draft; confirmed booking comes from server.','Drop initiates explicit booking command'),
('A09','Appointment creation and slot lookup','src/lib/components/scheduling/AppointmentForm.svelte','async','D/R/C','Form typing is local; latest service/day selection owns slot requests; show provisional creation after submit.','Capacity validation and idempotent create required; failed submit retains complete draft.','Keep Book/Create'),
('A10','Booking internal notes and labels','src/lib/components/scheduling/BookingDetailDrawer.svelte','async','O','Edit note/label inline; text remains visible with reserved pending status.','Patch revision reconciles; tag and booking partial outcomes remain separate until atomic endpoint exists.','Blur/Enter/debounce; remove note Save'),
('A11','Booking completion, cancellation and series','src/lib/components/scheduling/BookingDetailDrawer.svelte','async','C','Show action pending in place; keep unrelated calendar interactions usable.','Status, package reversal, accrual and stock warnings reflect committed outcome; no false rollback after partial commit.','Keep explicit consequence review'),
('A12','POS catalog enabled toggle','src/routes/(app)/pos/catalog/+page.svelte','createOptimistic','O','Thumb and intended state move immediately using existing overlay/pending Toggle.','Await canonical result; reject scoped operation; preserve newer queued intent.','Selection commits'),
('A13','POS cart quantities and tender draft','src/lib/components/pos/SellCart.svelte','<script','D','Recalculate local cart preview immediately, animate changed line/total without claiming payment.','Server validates totals/stock at explicit charge; draft remains coherent.','Local edits; keep Charge'),
('A14','Payment, ticket emission and closing shift','src/routes/(app)/pos/sell/+page.svelte','async','C/J','Immediate processing acknowledgement; confirmed receipt renders without waiting for ancillary refresh.','Unknown result reconciles by operation identity; never blindly retry or claim paid/emitted/closed.','Keep Charge/Issue/Close'),
('A15','CRM contact scalar fields','src/routes/(app)/crm/[contactId]/+page.svelte','async function patch','O','Show revised property immediately and subtle saving state.','Existing expectedUpdatedAt adapter rejects stale edit; errors retain draft and latest server baseline.','Blur/Enter/selection'),
('A16','Manual tags and entity links','src/lib/components/tags/TagsField.svelte','async function','O','Chip appears/disappears immediately with stable identity; tag creation uses provisional chip.','Desired membership/idempotent create plus server rules; rollback only this membership, not entire tag set.','Selection commits'),
('A17','CRM outbound messages','src/lib/components/crm/ContactChat.svelte','async','C/J','Pending bubble appears immediately; composer content retained for recovery; no duplicate echo.','Same clientId on retry; accepted, sent, delivered and read are distinct.','Keep Send'),
('A18','Stock table scalar edits and fill','src/routes/(app)/stock/items/+page.svelte','async','O','Reuse Claude cell overlay; keep active cell/focus and pending per row; coalesce refreshes for fill.','Add atomic stale-write guards first; partial batch results reconcile by row.','Cell commit/fill; no row Save'),
('A19','Stock UOM, packaging and recipe forms','src/routes/(app)/stock/items/[id]/+page.svelte','async','D','Instant local diagram/cost preview; preserve interdependent draft.','Validate and commit coherent configuration, keeping values on validation failure.','Keep Apply configuration'),
('A20','Stock submit/cancel and invoice actions','src/routes/(app)/stock/entries/[id]/+page.svelte','async','C','Immediate local processing state with stable preview; block duplicate command only.','Show ledger state only after commit; operation outcome required before retry.','Keep Submit/Cancel'),
('A21','Social integration asset toggle','src/routes/(app)/socials/settings/+page.svelte','async','O/C','Pending intended toggle replaces delayed snap; consequential disconnect has immediate pending row.','Check actual enabled outcome; connection removal remains confirmed.','Toggle autosaves; keep Disconnect'),
('A22','Sync, import, reindex, backups and provisioning','src/lib/components/finance/FinanceSyncBadge.svelte','<script','J','Show queued/requesting immediately; actual progress only when backend reports it.','Accepted request is not job completion; follow operation ID, resume observation, expose failure.','Keep Run/Sync/Import/Restore'),
('A23','Media/comments and metadata enrichment','src/routes/(app)/socials/posts/[postId]/+page.svelte','onMount','R','Keep mirrored content; independent reads parallelize and fill reserved regions.','Entity/query guards discard stale replies; unavailable differs from empty.','No Save'),
('A24','Notes create/edit/delete','src/lib/state/features/agent-notes.svelte.ts','create','O','New note and typing render immediately; deleting affects only selected note.','Recoverable draft, temp ID resolution, revision save and supported Undo; failure never silently loses text.','Typing autosaves; deletion policy explicit'),
('A25','Flow draft and node positions','src/lib/state/features/flow-editor.svelte.ts','saveFlow','O','Canvas responds immediately; per-entity queued save badge, no remount.','Capture revision; old success cannot clear newer draft; unsent draft survives navigation according to policy.','Debounce/drop; no routine Save'),
('A26','Skill metadata and chapter positions','src/lib/state/builder/skill-editor.core.svelte.ts','async','O','Title/text edits and chapter movement update locally with scoped pending status.','Coordinate-only rollback; acknowledged revision gating before publish; no whole-chapter-array restore.','Autosave draft; keep Publish'),
('A27','Publish, activate and execute agent/flow','src/lib/state/builder/skill-editor.core.svelte.ts','publish','C/J','Immediate publishing/starting state; preserve working draft and latest saved revision.','Wait for confirmed publish/run identity; execution completion follows job/stream, not request ack.','Keep Publish/Run'),
('A28','Personal dashboard resize/reorder','src/lib/components/dashboard/EditableGrid.svelte','function persist','L','Drag/resize follows input immediately and persists personal layout.','Scope local storage by user/org/dashboard; visual Done exits mode, not a network Save.','No Save'),
('A29','Publish dashboard organization default','src/lib/components/dashboard/EditableGrid.svelte','async function saveAsDefault','C','Mark publishing; do not freeze further personal editing.','Capture submitted layout; cache only acknowledged snapshot and preserve personal overrides.','Keep Set organization default'),
('A30','Appearance, locale and personal navigation','src/lib/state/ui/preference-sync.svelte.ts','putPreference','O','Theme/order/preference changes apply immediately.','Distinguish saved locally from synced; check HTTP status; scope/serialize writes and report retry.','Selection autosaves'),
('A31','Display name and ordinary profile properties','src/lib/components/users/EditableName.svelte','onCommit','O','Render draft in place on Enter/blur; reserve status affordance.','Rejected draft remains available; always settle busy state on exception.','No Save for scalar'),
('A32','Roles, access, credentials and security','src/lib/components/users/MemberAccessControls.svelte','async','C','Render pending intent with current effective access unchanged.','Server capabilities authoritative; atomic compound role changes or explicit partial state.','Explicit Apply/confirmation for security'),
('A33','Team resources and harmless preferences','src/lib/components/team/TeamSettingsView.svelte','createOptimistic','O/D','Reuse existing overlay for independent reversible fields; compound resource edits remain drafts.','Validate boundaries/capacity; shared error/status, do not assume every team setting harmless.','Scalar autosave; coherent form submit'),
('A34','Gateway tools and skills toggles','src/lib/state/agents/agent-tools.svelte.ts','optimistic','O/C','Immediate pending intent, retaining current optimistic behavior.','Scope by org/host/agent; late failure cannot revert newer intent; effective capabilities await RPC.','Toggle commit; sensitive policy explicit'),
('A35','Agent groups and membership movement','src/lib/state/features/agent-groups.svelte.ts','optimistic','O','Immediate group placement and provisional creation with stable identity.','Atomic membership move or partial reconciliation required; UI-only snapshot restore is insufficient.','Drop/selection commits after capability gate'),
('A36','Gateway chat and agent streaming','src/lib/services/gateway/chat-rpc.ts','async','C/J','Immediate queued bubble/thinking indicator; stream fills stable node.','Run ID idempotency and echo reconciliation; cancellation and completion require server signals.','Keep Send/Stop'),
('A37','Attachments upload, link, hide and restore','src/lib/components/attachments/AttachmentList.svelte','async function','O/C/J','Pending tile appears after file selection; link hiding/restoring is a reversible overlay.','Bytes transferred is not finalized; canonical linked file only after finalize. Unknown outcomes reconcile, recoverable hide supports Undo only via restore.','Selection uploads; permanent delete explicit'),
('A38','Notifications and approval commands','src/routes/(app)/notifications/+page.svelte','async function','C','Immediate per-request pending state, stable list and focus.','No optimistic permission grant or approval of consequential work; remove row only after ack.','Keep Approve/Deny'),
('A39','Dialogs, drawers, pickers and menus','src/lib/components/ui/foundations/Dialog.svelte','<script','L/R','Open shell and focus immediately; content fetch runs independently with first-load skeleton.','Keep dimensions/focus stable; failures render inline; close cleanup never waits solely on animation events.','No Save for opening; forms retain submit'),
('A40','Workforce polling and cross-view reads','src/lib/utils/live-polling.ts','export','R','Retain prior rows on background polling and soft refresh; animate only changed identity.','Authorized load remains source; coalesce invalidations, focus/reconnect revalidate, inactive tabs pause unnecessary work.','No Save'),
('A41','Charts, sparklines, graphs and workshop','src/lib/components/charts/Chart.svelte','prefersReducedMotion','L/R/J','Animate confirmed data delta or existing intentional canvas feedback; avoid full intro replay.','Reduced-motion policy covers engine/physics; never fabricate intermediate business values as committed results.','No Save unless a separate draft action'),
('A43','Notification delivery rules','src/routes/(app)/settings/notifications/+page.svelte','async','D/C','Rule form previews respond immediately; recipients/conditions/template remain one coherent draft.','Activation and external delivery intent are confirmed; qualified name-only metadata may later use O adapter.','Keep Apply rule/Activate'),
('A42','Gateway configuration editing and apply','src/lib/state/config/config.svelte.ts','export async function save','D/C','Local form previews and validation respond immediately; show apply/restart pending.','Preserve base-hash/version conflict and explicit restart/application result; not every config edit is safe autosave.','Keep Apply configuration')
]
rows.sort(key=lambda r:r[0])
out=[]
for id,title,source,needle,policy,intent,settle,gesture in rows:
 p=ROOT/'minion_hub'/source
 text=p.read_text();line=next((i for i,l in enumerate(text.splitlines(),1) if needle in l),None)
 if line is None:line=1
 out.append(dict(id=id,family=title,source='minion_hub/'+source,line=line,policy=policy,immediate=intent,settlement=settle,gesture=gesture))
(HERE/'catalog.json').write_text(json.dumps(out,indent=2)+'\n')
md=['# Interaction policy catalogue','','Policies: L local presentation; R asynchronous read; O optimistic reversible mutation; D coherent draft; C confirmed command; J long-running operation. Combined policies require the operation-specific branch, not a blanket classification for the page. Source anchors identify the owning surface; detailed AS-IS evidence lives in the three domain reports. Targets below are proposed.','','| ID / family | Source | Policy / gesture | Immediate feedback | Settlement and failure |','|---|---|---|---|---|']
for r in out:
 md.append(f"| {r['id']} — {r['family']} | [{r['source']}](../../{r['source']}):{r['line']} | {r['policy']} — {r['gesture']} | {r['immediate']} | {r['settlement']} |")
(HERE/'CATALOG.md').write_text('\n'.join(md)+'\n')
print(len(out),'interaction families')
